import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import { MessageCircle, X, Send, Check, ShieldAlert, Sparkles, Smile, HelpCircle, Phone, ArrowUpRight } from "lucide-react";

interface ChatMessage {
  id: string;
  sender: "bot" | "user";
  text: string;
  timestamp: string;
}

export default function WhatsAppSupport() {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "init",
      sender: "bot",
      text: "Namaste! I am Veda-V, your smart vending platform assistant. Are you looking to rent, purchase, or design a custom branded kiosk today?",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [inputText, setInputText] = useState<string>("");
  const [isTyping, setIsTyping] = useState<boolean>(false);
  
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Quick preset questions
  const presetQueries = [
    { q: "Do you ship across India / globally?", key: "shipping" },
    { q: "What is your monthly lease contract covers?", key: "lease" },
    { q: "How does the UPI Cashless payment tech integrate?", key: "upi" },
    { q: "Can I print custom decals or vinyl wraps?", key: "branding" }
  ];

  const queryResponses: Record<string, string> = {
    shipping: "Yes! Aura Smart Metric ships to all Tier-1 and Tier-2 regions (including Mumbai, Bangalore, Delhi NCR, and Pune) as well as global commercial terminals. Standard transit takes 3-5 business days, including full calibration check.",
    lease: "Our Monthly Lease program is 100% full-service. It includes: dynamic cashless gateway licensing, 24/7 automated stock alert synchronization, and free standard emergency technician dispatch on all parts. There are zero hidden fees.",
    upi: "All smart nodes are equipped with ultra-fast offline UPI autogenerated QR code display capabilities. Users scan, confirm on phone, and our server coordinates the instant release loop in less than 2.8 seconds.",
    branding: "Absolutely! Every machine supports full visual wraps. In our Customizer section, you can select accent colors, upload your corporate logo, and program dynamic scrolling LED marquee greetings directly!"
  };

  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages, isTyping]);

  const handleSendMessage = (text: string, responseKey?: string) => {
    if (!text.trim()) return;

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text: text,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText("");
    setIsTyping(true);

    // Simulate response delay
    setTimeout(() => {
      let replyText = "That's a great question! One of our commercial sales engineers will coordinate with you shortly. Feel free to use our Rent/Buy Calculator or Enquiry Form for a complete pricing quote!";
      
      if (responseKey && queryResponses[responseKey]) {
        replyText = queryResponses[responseKey];
      } else {
        // Keyword parsing fallback
        const lower = text.toLowerCase();
        if (lower.includes("price") || lower.includes("cost") || lower.includes("rent") || lower.includes("buy")) {
          replyText = "We offer flexible models! Monthly leases start at just $150/month (HydroCell Max) while outright purchases begin at $3,900. Try our interactive 'Cost Calculator' tab to see detailed cap-ex calculations!";
        } else if (lower.includes("custom") || lower.includes("logo") || lower.includes("brand")) {
          replyText = "Our customizer is fully interactive! You can pick primary accent colors, upload branding graphics, and even write your marquee ticker text to see it map in real time inside our 'Design Kiosk' tab!";
        } else if (lower.includes("upi") || lower.includes("pay") || lower.includes("card") || lower.includes("payment")) {
          replyText = "Our cashless payload interfaces with UPI, PhonePe, Paytm, GooglePay, and standard NFC swipe cards with instant cloud telemetry reporting. It's safe, 100% automated, and requires zero coin hopper refills.";
        }
      }

      const botMsg: ChatMessage = {
        id: `bot-${Date.now()}`,
        sender: "bot",
        text: replyText,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setMessages((prev) => [...prev, botMsg]);
      setIsTyping(false);
    }, 1200);
  };

  return (
    <div className="fixed bottom-6 right-6 z-[110] font-sans">
      
      {/* Floating Messenger trigger widget */}
      <AnimatePresence>
        {!isOpen && (
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.8, opacity: 0 }}
            className="flex flex-col items-end"
          >
            {/* Pop bubble notice */}
            <div className="bg-slate-900 border border-teal-500/30 px-3.5 py-1.5 rounded-2xl text-[10px] text-white font-mono uppercase tracking-wider mb-2 shadow-lg flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-400 animate-ping" />
              <span>Ask Offline Assistant</span>
            </div>

            <button
              onClick={() => setIsOpen(true)}
              className="h-14 w-14 rounded-full bg-emerald-500 hover:bg-emerald-400 text-slate-950 flex items-center justify-center shadow-[0_10px_30px_rgba(16,185,129,0.4)] hover:scale-105 duration-200"
            >
              <MessageCircle className="h-6 w-6" />
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Expanded Live Chat Overlay Column */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ y: 50, scale: 0.95, opacity: 0 }}
            animate={{ y: 0, scale: 1, opacity: 1 }}
            exit={{ y: 50, scale: 0.95, opacity: 0 }}
            className="bg-slate-900 border border-white/10 rounded-3xl w-[320px] sm:w-[360px] h-[480px] shadow-2xl flex flex-col overflow-hidden relative"
          >
            {/* Chat header panel */}
            <div className="bg-gradient-to-r from-slate-950 to-slate-900 p-4 border-b border-white/5 flex items-center justify-between relative">
              <div className="flex items-center gap-3">
                <div className="relative">
                  <div className="h-10 w-10 rounded-full bg-emerald-500/10 border border-emerald-400/20 flex items-center justify-center text-emerald-400">
                    <Sparkles className="h-5 w-5" />
                  </div>
                  <span className="absolute bottom-0 right-0 h-2.5 w-2.5 rounded-full bg-emerald-400 border-2 border-slate-900" />
                </div>
                <div>
                  <h4 className="text-xs font-bold font-mono uppercase tracking-wider text-white">Veda-V Smart Bot</h4>
                  <span className="text-[9px] text-emerald-400 font-mono tracking-widest block uppercase">Telemetry Active</span>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <a
                  href="https://wa.me/919999999999"
                  target="_blank"
                  rel="noreferrer"
                  className="p-1.5 rounded-lg hover:bg-white/5 text-slate-400 hover:text-white transition-colors"
                  title="Direct WhatsApp link"
                >
                  <ArrowUpRight className="h-4 w-4" />
                </a>
                <button
                  onClick={() => setIsOpen(false)}
                  className="p-1.5 rounded-lg hover:bg-white/5 text-slate-400 hover:text-white transition-all"
                >
                  <X className="h-4 w-4" />
                </button>
              </div>
            </div>

            {/* Conversation list */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-950/25">
              {messages.map((m) => (
                <div
                  key={m.id}
                  className={`flex ${m.sender === "user" ? "justify-end" : "justify-start"}`}
                >
                  <div
                    className={`max-w-[85%] rounded-2xl p-3 text-xs leading-relaxed ${
                      m.sender === "user"
                        ? "bg-emerald-500 font-semibold text-slate-950 rounded-tr-none"
                        : "bg-slate-900 border border-white/5 text-slate-200 rounded-tl-none"
                    }`}
                  >
                    <p>{m.text}</p>
                    <span className="text-[8px] font-mono text-slate-400/70 block mt-1 text-right">
                      {m.timestamp}
                    </span>
                  </div>
                </div>
              ))}

              {/* Bot Typing bubble indicators */}
              {isTyping && (
                <div className="flex justify-start">
                  <div className="bg-slate-950 border border-white/5 rounded-2xl p-3">
                    <div className="flex gap-1">
                      <span className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-bounce" />
                      <span className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-bounce [animation-delay:0.2s]" />
                      <span className="h-1.5 w-1.5 rounded-full bg-slate-400 animate-bounce [animation-delay:0.4s]" />
                    </div>
                  </div>
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Static Preset buttons panel wrapper */}
            {messages.length === 1 && !isTyping && (
              <div className="p-3 border-t border-white/5 bg-slate-950/40 space-y-1.5">
                <span className="text-[8px] font-mono tracking-widest text-slate-500 uppercase block">Common B2B Inquiries:</span>
                <div className="flex flex-col gap-1">
                  {presetQueries.map((item, idx) => (
                    <button
                      key={idx}
                      onClick={() => handleSendMessage(item.q, item.key)}
                      className="text-left w-full text-[10px] text-teal-400 hover:text-white bg-slate-950 border border-white/5 p-2 rounded-xl transition-all block truncate"
                    >
                      {item.q}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Custom Input field block */}
            <div className="p-3 border-t border-white/5 bg-slate-950 font-sans">
              <div className="relative flex items-center">
                <input
                  type="text"
                  placeholder="Type a corporate inquiry..."
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") handleSendMessage(inputText);
                  }}
                  className="w-full bg-slate-900 border border-white/5 rounded-xl pl-3 pr-10 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none"
                />
                <button
                  onClick={() => handleSendMessage(inputText)}
                  className="absolute right-2 text-emerald-400 hover:text-white transition-colors"
                >
                  <Send className="h-4 w-4" />
                </button>
              </div>
            </div>

          </motion.div>
        )}
      </AnimatePresence>

    </div>
  );
}
